// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(RegularExpressionContext))]
    partial class RegularExpressionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApi.Models.RegularExpression", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("RegularExpressionGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Replace")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ReplaceValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RegularExpressionGroupId");

                    b.ToTable("RegularExpressions");
                });

            modelBuilder.Entity("WebApi.Models.RegularExpressionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("PreviewAfterConversion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PreviewBeforeConversion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("RegularExpressionGroups");
                });

            modelBuilder.Entity("WebApi.Models.RegularExpression", b =>
                {
                    b.HasOne("WebApi.Models.RegularExpressionGroup", null)
                        .WithMany("RegularExpressions")
                        .HasForeignKey("RegularExpressionGroupId");
                });

            modelBuilder.Entity("WebApi.Models.RegularExpressionGroup", b =>
                {
                    b.Navigation("RegularExpressions");
                });
#pragma warning restore 612, 618
        }
    }
}
